# -*- coding: utf-8 -*-
"""EEG_Signal_Simulation_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2rarNCtKbcmw0UX3W_gUIxS_9BImlq_
"""

import numpy as np

# ==============================
# CONFIG (Must Match Inference)
# ==============================
FS = 128              # Sampling frequency
N_CHANNELS = 14       # Total EEG channels
DURATION = 10         # seconds (>=5 required)
NOISE_LEVEL = 0.3     # Background noise strength

# ==============================
# Band Definitions
# ==============================
BANDS = {
    "theta": (4, 8),
    "alpha": (8, 13),
    "beta": (13, 30),
    "gamma": (30, 45)
}

# ==============================
# EEG Generator (Emotion-Free)
# ==============================
def generate_eeg(duration_sec=DURATION):
    t = np.linspace(0, duration_sec, FS * duration_sec)
    eeg = np.zeros((len(t), N_CHANNELS))

    for ch in range(N_CHANNELS):

        signal = np.zeros_like(t)

        # Add each frequency band
        for band_range in BANDS.values():
            freq = np.random.uniform(band_range[0], band_range[1])
            amplitude = np.random.uniform(5, 15)
            phase = np.random.uniform(0, 2*np.pi)

            signal += amplitude * np.sin(2 * np.pi * freq * t + phase)

        # Add Gaussian noise
        noise = NOISE_LEVEL * np.random.randn(len(t))
        signal += noise

        eeg[:, ch] = signal

    return eeg


# ==============================
# Test
# ==============================
if __name__ == "__main__":
    eeg_data = generate_eeg()
    print("EEG shape:", eeg_data.shape)

